SCHEMA_VERSION = 1
DATA_REVISION = 2
DISTRIBUTION_SIZE = 1024
ROUND_DIGITS = 6
PROBABILITY_TOLERANCE = 2e-4

DX_DICE_COUNT = 100
DX_CRITICAL_VALUES = range(2, 12)
SHIHAI_VALUES = range(20)

BACKTRACK_DICE_COUNT = 224
D10_DICE_COUNT = BACKTRACK_DICE_COUNT
LIVING_DEAD_DICE_COUNT = BACKTRACK_DICE_COUNT

DR_DICE_COUNT = 203
KAZANARI_VALUES = range(10)
FFT_SIZE = 4096
